#!/bin/sh

export SSL_OPTS=""
java -Djavax.net.ssl.keyStore=keyz/server.ks -Djavax.net.ssl.trustStore=keyz/server.ks -Djavax.net.ssl.keyStorePassword=password -jar server/target/server*dependencies.jar

